name: Hawn
version: '${version}'
author: Dianox
main: fr.dianox.hawn.Main
api-version: '1.16'
load: POSTWORLD
softdepend: [PlaceholderAPI, WorldGuard, WorldEdit, MVdWPlaceholderAPI, BattleLevels]
commands:
  hawn:
    description: Main menu for admins.
    usage: /<command> help
