name: Hawn
version: 1.1.4-Beta
author: Dianox
main: fr.dianox.hawn.Main
api-version: 1.13
LOAD: POSTWORLD
softdepend: [PlaceholderAPI, WorldGuard, WorldEdit, MVdWPlaceholderAPI, BattleLevels]
commands:
  hawn:
    description: Main menu for admins.
    usage: /<command> help