name: Hawn
version: 0.7.1-Alpha
author: Dianox
main: fr.Dianox.Hawn.Main
api-version: 1.13
LOAD: POSTWORLD
softdepend: [PlaceholderAPI, WorldGuard, WorldEdit, MVdWPlaceholderAPI]
commands:
  hawn:
    description: Main menu for admins.
    usage: /<command> help
